project:
  type: website

website:
  title: "Ashish Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Education
      - href: professional.qmd
      
  page-footer: 
    right: "&copy; 2024, Ashish Singh"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto
